### ISSUE TITLE
NetworkingDSC: Can not invoke resource on a system multi language

### ISSUE THREAD

**Issue by Erwan-loot** [dsccommunity/NetworkingDsc#464]
```powershell
OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64 bits
WindowsBuildLabEx    : 14393.3686.amd64fre.rs1_release.200504-1524
OsLanguage           : en-US
OsMuiLanguages       : {en-US, fr-FR}

Name                           Value
----                           -----
PSVersion                      5.1.14393.3471
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3471
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
# insert configuration here
```

Hi, 
I'm trying to deploy Windows 2016 Standard Core/GUI.
For your information
We download the iso in english, then we put a language pack in french.

I try to invoke this module with Ansible and the module WIN_DSC which works well in 7.4.0
There is an error in 8.0. Useless to put the ansible error here, i've checked the script of ansible directly and i've test myself
https://github.com/ansible-collections/ansible.windows/blob/main/plugins/modules/win_dsc.ps1

As you can see the module WIN_DSC try this 
```powershell
Invoke-DscResource -Method Get -Property @{Fake='fake'} -ModuleName @{ModuleName="NetworkingDsc"; ModuleVersion="8.0.0"} -Name NetAdapterName
```
to "trigger" the resource and check if we can invoke it

```powershell
> Invoke-DscResource -Method Get -Property @{Fake='fake'} -ModuleName @{ModuleName="NetworkingDsc"; ModuleVersion="8.0.0"} -Name NetAdapterName -verbose
VERBOSE: Effectuez l’opération « Invoquer une méthode CIM » avec les
paramètres suivants : « 'methodName' = ResourceGet,'className' =
MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration ».
VERBOSE: Un appel de méthode du Gestionnaire de configuration local est
arrivé de l'ordinateur WIN-MLA93M3G4EA avec le SID utilisateur
S-1-5-21-4236065641-2645614401-65003152-1000.
Échec de l’importation du module DSC_NetAdapterName avec l’erreur:
Impossible de trouver le fichier de données Windows PowerShell «
NetworkingDsc.Common.psd1» dans le répertoire «C:\Program Files\WindowsPow
erShell\Modules\NetworkingDsc\8.0.0\Modules\NetworkingDsc.Common\en-US\»
ou dans les répertoires de culture parents.
    + CategoryInfo          : InvalidOperation : (root/Microsoft/...gurat
   ionManager:String) [], CimException
    + FullyQualifiedErrorId : ImportModuleFailed
    + PSComputerName        : localhost

```

we can see the files in 8.0

```powershell
gci "C:\Program Files\WindowsPowerShell\Modules\NetworkingDsc\8.0.0\Modules\"


    Répertoire: C:\Program
    Files\WindowsPowerShell\Modules\NetworkingDsc\8.0.0\Modules


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       08/07/2020     14:45                DscResource.Common
d-----       08/07/2020     14:45                NetworkingDsc.Common

gci "C:\Program Files\WindowsPowerShell\Modules\NetworkingDsc\8.0.0\Modules\NetworkingDsc.Common\en-US"



Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       21/06/2020     19:36           1764 NetworkingDsc.Common.stri
                                                 ngs.psd1
```
The same command in 7.4.0.0

```powershell
> Invoke-DscResource -Method Get -Property @{Fake='fake'} -ModuleName @{ModuleName="NetworkingDsc"; ModuleVersion="7.4.0.0"} -Name NetAdapterName -verbose
VERBOSE: Effectuez l’opération « Invoquer une méthode CIM » avec les paramètres suivants :
« 'methodName' = ResourceGet,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration ».
VERBOSE: Un appel de méthode du Gestionnaire de configuration local est arrivé de l'ordinateur
WIN-MLA93M3G4EA avec le SID utilisateur S-1-5-21-4236065641-2645614401-65003152-1000.
Propriété non définie Fake
 Ligne : 8, caractère : 2
 Mémoire tampon :
";
    Fake = "fake";
};^
insta
    + CategoryInfo          : SyntaxError: (root/Microsoft/...gurationMan
   ager:String) [], CimException
    + FullyQualifiedErrorId : MiClientApiError_Failed
    + PSComputerName        : localhost

VERBOSE: L’opération « Invoquer une méthode CIM » est terminée.
VERBOSE: Le temps nécessaire à l'exécution de la tâche de configuration est de 1.087 secondes
```
IT works 

The code of the function Get-localizeddata has changed. it is now located in a folder "Common". it look for the files .strings.psd1 and .psd1. Previously in 7.4.0 it was looking for .strings.psd1 only

**Comment by PlagueHO** [comment]
Hi @Erwan-loot - you are right, we moved the `Get-LocalizedData` to a new Common module (https://github.com/dsccommunity/DscResource.Common) in this release. This common module is used by most resources now, but haven't come across an issue with alternate localization.

If you try to import the module `NetworkingDsc.Common` using `Import-Module 'C:\Program Files\WindowsPowerShell\Modules\NetworkingDsc\8.0.0\Modules\NetworkingDsc.Common' do you get the error?

**Comment by PlagueHO** [comment]
Hey @johlju - have you come across anything like this in SqlServerDsc or any of the others? I've tried switching my OS to non en-US and haven't been able to replicate the issue.

**Comment by johlju** [comment]
No, but then I haven’t run it on an non en-US system for a while. The only similar issue I came across is when LCID is set to 127 on my macOS. 

I had a Spanish Windows Server in my lab before to test SqllServerDsc but  I removed it a while back and haven’t tried the new Get-LocalizedData. I used the Spanish OS because it is Spanish without adding a language pack, but maybe that would  behave differently than having an en-US OS with (French) language pack. We should test both.

**Comment by PlagueHO** [comment]
Thanks @johlju - I'll go install a clean version of Windows Server 2016 with French language pack and see if I can replicate the problem. But actually thinking back I recall I wasn't comfortable with the logic around `Get-LocalizedData` and raised an issue: https://github.com/dsccommunity/DscResource.Common/issues/37

So perhaps I'll need to revisit this and move a rewrite forward.

**Comment by johlju** [comment]
Yes I’m all for a rewrite. 

I was thinking that maybe in the issue scenario the account SYSTEM has a different LCID. So to be able to repro this we should verify what the LCID is actually set to what value In the issue scenario? 🤔

**Comment by PlagueHO** [comment]
I'll see if I can repro first and then work on a rewrite.

**Comment by PlagueHO** [comment]
I haven't been able to repro it yet on a clean WS2016 build with default UI culture set to `fr-FR`:
![image](https://user-images.githubusercontent.com/7589164/87832159-6f5c4d80-c8d9-11ea-9eb2-ee3a8963be95.png)

**Comment by PlagueHO** [comment]
And another better test:
![image](https://user-images.githubusercontent.com/7589164/87832825-f958e600-c8da-11ea-9391-43254283d01d.png)

**Comment by johlju** [comment]
There is a similar issue in SqlServerDsc now https://github.com/dsccommunity/SqlServerDsc/issues/1596.

**Comment by Erwan-loot** [comment]
> Hi @Erwan-loot - you are right, we moved the `Get-LocalizedData` to a new Common module (https://github.com/dsccommunity/DscResource.Common) in this release. This common module is used by most resources now, but haven't come across an issue with alternate localization.
> 
> If you try to import the module `NetworkingDsc.Common` using `Import-Module 'C:\Program Files\WindowsPowerShell\Modules\NetworkingDsc\8.0.0\Modules\NetworkingDsc.Common' do you get the error?

Yes,
I would like to clarify. i'm on a english version of windows server 2016 then, i'll install the french language with a CAB file.
```powershell
"Importing the NetworkingDSC module with error to find networkingdsc.common.psd1 data file cannot be found in directory c:\program files\windowspowershell\modules\networkingdsc\8.0.0\modules\networkingdsc.common\en-US or a parent directory"
```

**Comment by johlju** [comment]
@PlagueHO  I was able to repro this with the German Windows Server ISO.

Added a issue here with a unit test that can reproduce the problem:
https://github.com/dsccommunity/DscResource.Common/issues/50

**Comment by PlagueHO** [comment]
Thanks @Erwan-loot - awesome stuff @johlju .

**Comment by PlagueHO** [comment]
Thanks to @johlju there is now a new version of DSCResource.Common- so will need to trigger a new release of this module once it is built.

**Comment by johlju** [comment]
@PlagueHO I released a new version, so you can do a new release of this module.
