### ISSUE TITLE
Type mismatch issue with setting Dhcp to disabled

### ISSUE THREAD

**Issue by nmdange2** [dsccommunity/NetworkingDsc#470]
#### Details of the scenario you tried and the problem that is occurring
I am running Test-DscConfiguration with a configuration that disables Dhcp and sets a static IP address.  This configuration is unchanged but has stopped working in a recent update.  I believe it is related to changes from pull request #402 which added type checking to Test-DscParameterState.

#### Verbose logs showing the problem
VERBOSE: [computername]:                            [[NetIPInterface]DisableDhcpHostvNIC] NOTMATCH: Type mismatch    for property 'Dhcp' Current state type is 'Microsoft.PowerShell.Cmdletization.GeneratedTypes.NetIPInterface.Dhcp' and   desired type is 'System.String'. (DRC0019)                                                                              

#### Suggested solution to the issue
The new version of Test-DscParameterState has a parameter to ignore the type. I think adding this option to the call in NetIPInterface will fix the problem.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# From Example
Configuration IPAddress_AddingStaticIPWithPrefix_Config
{
    Import-DscResource -Module NetworkingDsc

    Node localhost
    {
        NetIPInterface DisableDhcp
        {
            InterfaceAlias = 'Ethernet'
            AddressFamily  = 'IPv4'
            Dhcp           = 'Disabled'
        }

        IPAddress NewIPv4Address
        {
            IPAddress      = '192.168.10.5/24'
            InterfaceAlias = 'Ethernet'
            AddressFamily  = 'IPV4'
        }
    }
}
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
8.2

**Comment by PlagueHO** [comment]
Thanks for raising this @nmdange2  - I'll get onto a fix now.

**Comment by PlagueHO** [comment]
Hi @nmdange2 - I noticed that the version you're using is v8.2.0- however, the latest version is v8.1.0. Were you using a version downloaded from GitHub? I'm just wanting to make sure I implement appropriate tests to validate this.

**Comment by nmdange2** [comment]
Sorry that was a typo, I'm on the latest that's on Powershell Gallery.

**Comment by PlagueHO** [comment]
Sweet - no worries, I replicated the issue in the unit tests and submitted a PR to fix.
