### ISSUE TITLE
Address is not in the correct format.

### ISSUE THREAD

**Issue by NFCES** [dsccommunity/NetworkingDsc#478]
I am not having much luck with pushing the DnsServerAddress_Config using the following script. I have tried various formats such as (with signal and double quotes). Please advise.

**Examples:**
'10.200.2.8','10.200.2.9'
'10.200.2.8', '10.200.2.9'
'10.200.2.8';'10.200.2.9'
'10.200.2.8', '10.200.2.9'
'10.200.2.8' '10.200.2.9'

**Script:**
<#
    .DESCRIPTION
    Configure DNS Server for the Ethernet adapter.
#>
Configuration DnsServerAddress_Config
{
    Import-DscResource -Module NetworkingDsc

    Node localhost
    {
        DnsServerAddress DnsServerAddress
        {
            Address        = "10.200.2.8","10.200.2.9"
            InterfaceAlias = 'Ethernet'
            AddressFamily  = 'IPv4'
            Validate       = $true
        }
    }
}

**Error:**
PowerShell DSC resource DSC_DnsServerAddress failed to execute Test-TargetResource functionality with error message: Address '10.200.2.8 10.200.2.9' is not in the correct format. Please correct the Address parameter in the configuration and try again. (DRC0011) Parameter name: Address

**Comment by phbits** [comment]
@NFCES - I found that commenting out `Validate = $true` will result in a successful configuration. Full config is:

```
Configuration DnsServerAddressTest
{
	Import-DscResource -ModuleName NetworkingDsc

	DnsServerAddress Ethernet_2_DnsServerAddress
	{
	        Address        = '10.200.2.8','10.200.2.9'
	        InterfaceAlias = 'Ethernet 2'
	        AddressFamily  = 'IPv4'
#	        Validate       = $true
	}
}

```

**Comment by PlagueHO** [comment]
Hi @NFCES, @phbits - that is quite strange. The `Validate:$true` parameter can cause some problems when assigning DNS, but it doesn't usually show up like this.

What happens if you run the command:
```powershell
Set-DnsClientServerAddress -InterfaceAlias 'Ethernet' -ServerAddresses "10.200.2.8","10.200.2.9" -Validate
```

on the machine in question? Does it report back the error you see?

**Comment by NFCES** [comment]
Figured it out. The following format appears to work.

Address        = "10.200.2.8","10.200.2.9"
            InterfaceAlias = 'Ethernet'
            AddressFamily  = 'IPv4'
            Validate       = $true
        }

**Comment by PlagueHO** [comment]
That is really strange @NFCES - I'd expect this to work:
`Address        = '10.200.2.8','10.200.2.9'`

These would also work:
```powershell
Address        = @('10.200.2.8','10.200.2.9')
Address        = @("10.200.2.8","10.200.2.9")
Address        = "10.200.2.8","10.200.2.9"
```

But I'll close this one if that is OK? Feel free to reopen it.
