### ISSUE TITLE
Netbios: Fails to disable when NIC has link down

### ISSUE THREAD

**Issue by johlju** [dsccommunity/NetworkingDsc#511]
### Problem description

When a NIC has link down it fails to set the Netbios to disabled.

### Verbose logs

```text
PowerShell DSC resource DSC_NetBios failed to execute Set-TargetResource functionality with error message: System.InvalidOperationException: An error result of '84' was returned when attemting to set NetBIOS for Interface 'Intel(R) 82574L GigabitNetwork Connection #2' configuration to 'Disable'.
+ CategoryInfo : InvalidOperation: (:) [], CimException
+ FullyQualifiedErrorId : ProviderOperationExecutionFailure
+ PSComputerName : node01

The SendConfigurationApply function did not succeed.
+ CategoryInfo : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
+ FullyQualifiedErrorId : MI RESULT 1
+ PSComputerName : node01
```

### DSC configuration

```powershell
NetBios DisableNetBios
{
    InterfaceAlias = 'Ethernet'
    Setting        = 'Disable'
}
```

### Suggested solution

Check wehter the NIC has link down and set through registry instead.

### Operating system the target node is running

```text
Windows Server 2019
```

### PowerShell version and build the target node is running

```text
WPS 5.1
```

### NetworkingDsc version

```text
8.2.0
```

**Comment by PlagueHO** [comment]
Hi @johlju - there are two possible approaches here:
1. Implement a fall-back method that sets the registry setting in the link is down. How would we detect this - is there an exception that is thrown or do we need to first detect this some other way?
2. Only use the registry setting method - regardless of link-state?

Any thoughts? It seems like an easy enough change, but option 1 will require good unit tests that validate the approach. Either way, I'd recommend a proxy function is created that can implement this (make it easier to test).

**Comment by johlju** [comment]
Thanks for the quick response @PlagueHO. We got this on a machine, but submitted the issue for a colleague of mine and asked him to look into a way to possible resolve this, so we could propose a PR. I’m hoping we can get back with more information around this. 😊

**Comment by PlagueHO** [comment]
My assumption is that the setting won't be read from the registry except on specific adapter events. So, setting it that way for adapters that have a link up won't disable NetBios immediately. But if we can verify this then we could just implement the registry method always.

**Comment by phbits** [comment]
This was fixed via [PR#479](https://github.com/dsccommunity/NetworkingDsc/pull/479).

**Comment by PlagueHO** [comment]
@phbits - you are quite correct! v9.0.0 has now been released and it has this fix in it. @johlju - can you check to see if this new version solves the issue?

**Comment by johlju** [comment]
I close this while we investigate if this has been fixed. Thanks @phbits!
