### ISSUE TITLE
Firewall resource isn't properly identifying some built-in rules on Windows Server (2019 and 2022 tested)

### ISSUE THREAD

**Issue by kburkeland** [dsccommunity/NetworkingDsc#522]
Hey all! I'm seeing some issues with disabling some built-in rules on Windows Server 2019 / 2022. There seem to be a few different rule groups that this is affecting, however, I'm just going to use a rule from the "AllJoyn Router" group of rules for the example found below.

`Firewall Inbound_AllJoyn_Router_TCP_In {
            Ensure = 'Present'
            Enabled = 'False'
            Name = 'AllJoyn Router (TCP-In)'
}`

This does not update the built-in rule but instead creates a new rule with the same name and default settings that aren't defined such as the assigned profiles. Specifying directions and the corresponding profiles in the configuration still show the same functionality. Thoughts?

"Cast to Device functionality" is the other group of rules I'm seeing the issue with. Will update in the comments if I find more.

**Comment by kburkeland** [comment]
Found more rules/rule groupings. Looks like "Delivery Optimization", "DIAL protocol server", "mDNS", and "Microsoft Media Foundation" are all not being recognized/found by the Firewall resource. The same tests were performed as mentioned above.

**Comment by PlagueHO** [comment]
Hi @kburkeland - what happens when you run:
```powershell
Get-NetFirewallRule -Name 'AllJoyn Router (TCP-In) | FL *
```
On the machine? Does it return a rule?

**Comment by kburkeland** [comment]
Get-NetFirewallRule -Name 'AllJoyn Router (TCP-In)' | FL *
Get-NetFirewallRule: No MSFT_NetFirewallRule objects found with property 'InstanceID' equal to 'AllJoyn Router (TCP-In)'.  Verify the value of the property and retry.

**Comment by kburkeland** [comment]
Hold up, might have found the issue here. Switching the Name to DisplayName does return a result. Name of the rule actually ends up being 'AllJoyn-Router-In-TCP'. Here's hoping it's that easy of a fix.

Get-NetFirewallRule -DisplayName 'AllJoyn Router (TCP-In)' | FL *

Name                          : AllJoyn-Router-In-TCP
ID                            : AllJoyn-Router-In-TCP
DisplayName                   : AllJoyn Router (TCP-In)
Group                         : @FirewallAPI.dll,-37002
Enabled                       : True
Profile                       : Domain, Private
Platform                      : {}
Direction                     : Inbound
Action                        : Allow
EdgeTraversalPolicy           : Block
LSM                           : False
PrimaryStatus                 : OK
Status                        : The rule was parsed successfully from the store. (65536)
EnforcementStatus             : NotApplicable
PolicyStoreSourceType         : Local
Caption                       :
Description                   : Inbound rule for AllJoyn Router traffic [TCP]
ElementName                   : @FirewallAPI.dll,-37003
InstanceID                    : AllJoyn-Router-In-TCP
CommonName                    :
PolicyKeywords                :
PolicyDecisionStrategy        : 2
PolicyRoles                   :
ConditionListType             : 3
CreationClassName             : MSFT|FW|FirewallRule|AllJoyn-Router-In-TCP
ExecutionStrategy             : 2
Mandatory                     :
PolicyRuleName                :
Priority                      :
RuleUsage                     :
SequencedActions              : 3
SystemCreationClassName       :
SystemName                    :
DisplayGroup                  : AllJoyn Router
LocalOnlyMapping              : False
LooseSourceMapping            : False
Owner                         :
Platforms                     : {}
PolicyStoreSource             : PersistentStore
Profiles                      : 3
RemoteDynamicKeywordAddresses : {}
RuleGroup                     : @FirewallAPI.dll,-37002
StatusCode                    : 65536
PSComputerName                :
CimClass                      : root/standardcimv2:MSFT_NetFirewallRule
CimInstanceProperties         : {Caption, Description, ElementName, InstanceID…}
CimSystemProperties           : Microsoft.Management.Infrastructure.CimSystemProperties

**Comment by kburkeland** [comment]
Looks like the issue is just a mismatch between the rule names and display names. Appreciate the assistance @PlagueHO!
